version: '3'
services:
  # App server provisioning
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '3000:3000'
    networks:
      - localdev
    volumes:
      - './:/app'
      - './.env.test:/app/.env.test'
    command: bash -c 'sh start_local.sh'

  # Memcached provisioning
  memcached:
    image: memcached
    ports:
      - '11211:11211'
    networks:
      - localdev

  postgres:
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rootPassword
    networks:
      - localdev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  localdev:
    driver: bridge
volumes:
  mysql-volume:
