FROM node:18
# Set working directory

RUN mkdir -p /app
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json /app

# Install dependencies
RUN npm install

# Copy source code
COPY . /app
# Expose port 3000 for the app to listen on
EXPOSE 3000
# Start the app
# CMD [ "npm", "run", "start" ]